 export const inputs = [
    {
      id: 1,
      name: "name",
      type: "text",
      label: "Full Name",
      required: true,
      pattern: "^[A-Z ]{3,}$",
      errorMessage:
        "Name should be in capital letters and at least 3 characters long.",
    },
    {
      id: 2,
      name: "dob",
      type: "date",
      label: "Date of Birth",
      required: true,
      errorMessage: "Date of Birth is required.",
    },
    {
      id: 3,
      name: "gender",
      type: "text",
      label: "Gender",
      required: true,
      errorMessage: "Gender is required.",
    },
    {
      id: 4,
      name: "bloodGroup",
      type: "text",
      label: "Blood Group",
      required: false,
      pattern: "^(A|B|AB|O)[+-]$",
      errorMessage: "Enter valid blood group (e.g., A+, B-, O+).",
    },
    {
      id: 5,
      name: "religionOrCaste",
      type: "text",
      label: "Religion/Caste",
      required: true,
    },
    {
      id: 6,
      name: "dayScholar",
      type: "text",
      label: "Day Scholar / Hosteller",
      required: true,
      pattern: "^(Day Scholar|Hosteller)$",
      errorMessage: "Must be either 'Day Scholar' or 'Hosteller'.",
    },
    {
      id: 7,
      name: "admittedCategory",
      type: "text",
      label: "Admitted Category",
      required: true,
    },
    {
      id: 8,
      name: "stateOfResidence",
      type: "text",
      label: "State of Residence",
      required: true,
    },
    {
      id: 9,
      name: "nationality",
      type: "text",
      label: "Nationality",
      required: true,
      pattern: "^[A-Za-z ]+$",
      errorMessage: "Nationality is required and should contain only letters.",
    },
    {
      id: 10,
      name: "fathersName",
      type: "text",
      label: "Father's Name",
      required: true,
      pattern: "^[A-Za-z ]{3,}$",
      errorMessage: "Father's Name must be at least 3 characters.",
    },
    {
      id: 11,
      name: "mothersName",
      type: "text",
      label: "Mother's Name",
      required: true,
      pattern: "^[A-Za-z ]{3,}$",
      errorMessage: "Mother's Name must be at least 3 characters.",
    },
    {
      id: 12,
      name: "guardianName",
      type: "text",
      label: "Guardian Name",
      required: true,
      errorMessage: "Guardian's name is required.",
    },
    {
      id: 13,
      name: "occupation",
      type: "text",
      label: "Occupation",
      required: true,
    },
    {
      id: 14,
      name: "relationShip",
      type: "text",
      label: "Relationship",
      required: true,
    },
    {
      id: 15,
      name: "aadhar",
      type: "text",
      label: "Aadhar Number Of Student",
      required: true,
      pattern: "^[2-9]{1}[0-9]{11}$",
      errorMessage: "Enter a valid 12-digit Aadhar number.",
    },
    {
      id: 16,
      name: "emailIDStudent",
      type: "email",
      label: "Email (Student)",
      required: true,
      pattern: "^[\\w.-]+@[\\w.-]+\\.\\w{2,}$",
      errorMessage: "Enter a valid email address.",
    },
    {
      id: 17,
      name: "emailIDFather",
      type: "email",
      label: "Email (Father)",
      pattern: "^[\\w.-]+@[\\w.-]+\\.\\w{2,}$",
      errorMessage: "Enter a valid email address.",
    },
    {
      id: 18,
      name: "emailIDGuardian",
      type: "email",
      label: "Email (Guardian)",
      pattern: "^[\\w.-]+@[\\w.-]+\\.\\w{2,}$",
      errorMessage: "Enter a valid email address.",
    },
    {
      id: 19,
      name: "permanentAddress",
      placeholder: "Door/House, PO, City, District",
      type: "text",
      label: "Permanent Address",
      required: true,
      errorMessage: "Permanent Address is required.",
    },
    {
      id: 36,
      name: "permanentAddressPhone",

      type: "text",
      label: "Permanent Address Phone",
      required: true,
      errorMessage: "Permanent Address Phone is required.",
    },
    {
      id: 20,
      name: "contactAddress",
            placeholder: "Door/House, PO, City, District",

      type: "text",
      label: "Contact Address",
      required: true,
      errorMessage: "Contact Address is required.",
    },
    {
      id: 37,
      name: "contactAddressPhone",

      type: "text",
      label: "Contact Address Phone",
      required: true,
      errorMessage: "Contact Address Phone is required.",
    },
    {
      id: 21,
      name: "localGuardianAddress",
            placeholder: "Door/House, PO, City, District",

      type: "text",
      label: "Local Guardian Address",
    },
    {
      id: 38,
      name: "localGuardianAddressPhone",
      type: "text",
      label: "Local Guardian Address Phone",
    },
    {
      id: 22,
      name: "qualifiedExam",
      type: "text",
      label: "Qualified Exam",
      required: true,
      errorMessage: "Qualified Exam is required.",
    },
    {
      id: 24,
      name: "qualifiedExamRegisterNo",
      type: "text",
      label: "Exam Register Number",
      required: true,
      pattern: "^[A-Za-z0-9-]{3,}$",
      errorMessage: "Register Number is required.",
    },
    {
      id: 25,
      name: "qualifiedExamInstitution",
      type: "text",
      label: "Exam Institution",
      required: true,
      errorMessage: "Exam Institution is required.",
    },
    {
      id: 26,
      name: "TCNumber",
      type: "text",
      label: "TC Number",
      required: true,
      errorMessage: "TC Number is required.",
    },
    {
      id: 27,
      name: "dateOfTC",
      type: "date",
      label: "Date of TC",
      required: true,
      errorMessage: "Date of TC is required.",
    },
    {
      id: 28,
      name: "TCIssuedInstitution",
      type: "text",
      label: "TC Issued By",
      required: true,
      errorMessage: "Issuing Institution is required.",
    },

    {
      id: 29,
      name: "marksOfQualifyingInstitutionType",
      type: "text",
      label: "Percentage / CGPA",
      required: true,
      errorMessage: "Result type is required.",
    },
    {
      id: 30,
      name: "marksOfQualifyingInstitution",
      type: "text",
      label: "Total",
      required: true,
      pattern: "^[0-9.]+$",
      errorMessage: "Enter a valid value",
    },
    {
      id: 39,
      name: "physics",
      placeholder: "Higher Secondary Physics Score",
      type: "text",
      label: "Physics",
      pattern: "^[0-9]{1,3}$",
      errorMessage: "Enter a valid physics mark.",
      required: true,
    },

    {
      id: 40,
      name: "chemistry",
      required: true,
      placeholder: "Higher Secondary Chemistry Score",
      type: "text",
      label: "Chemistry",
      pattern: "^[0-9]{1,3}$",
      errorMessage: "Enter a valid chemistry mark.",
    },
    {
      id: 41,
      name: "maths",
      placeholder: "Higher Secondary Math Score",
      type: "text",
      label: "Mathematics",
      required: true,
      pattern: "^[0-9]{1,3}$",
      errorMessage: "Enter a valid maths mark.",
    },
    {
      id: 31,
      name: "entranceRollNumber",
      type: "text",
      label: "Entrance Roll Number",
      required: true,
      errorMessage: "Entrance Roll number is required.",
    },
    {
      id: 32,
      name: "entranceRank",
      type: "text",
      label: "Entrance Rank",
      pattern: "^[0-9]+$",
      errorMessage: "Rank must be numeric.",
      required: true,
    },
    {
      id: 33,
      name: "bankAccountNo",
      type: "text",
      label: "Bank Account No",
      pattern: "^[0-9]{9,18}$",
      errorMessage: "Enter a valid bank account number.",
      required: true,
    },
    {
      id: 34,
      name: "bankIFSCCode",
      type: "text",
      label: "Bank IFSC Code",
      pattern: "^[A-Z]{4}0[A-Z0-9]{6}$",
      errorMessage: "Enter a valid IFSC code (e.g., SBIN0001234).",
      required: true,
    },
    {
      id: 35,
      name: "bankName",
      type: "text",
      label: "Bank Name",
      required: true,
    },
  ];